version: "3.9"
services:
  frontend:
    build:
      context: ./Frontend/Producer/producer-ui
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./Frontend/Producer/producer-ui:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend/node-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./Backend/node-server:/app
    environment:
      - NODE_ENV=development
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend